---
- name: ping to all the node
  hosts: server
  gather_facts: false
  tasks:
    - name: check the HTTP server
      uri:
        url: "http://{{ ansible_host }}"
      register: result

    - name: print out the result
      debug: var=result
