---
- name: data vis containers based on github.com/nerdalert/cloud-bandwidth
  hosts: client
  vars:
    repo: https://github.com/nerdalert/cloud-bandwidth
  gather_facts: false
  pre_tasks:
    - name: install the pre-requisite apt packages
      apt: name={{ item }} state=present update_cache=false
      items:
        - docker.io
        - python-pip
      become: true

    - name: install python packages
      pip: name={{ item }}
      items:
        - docker-py
        - docker-compose
      become: true

    - name: clone the cloud-bandwidth git repo
      git:
        repo: "{{ repo }}"
        dest: /tmp/cloud-bandwidth
        update: yes
        ssh_opts: "-o StrictHostKeyChecking=no"
      register: git

    - name: fire up the data vis containers!
      docker_service:
        project_src: /tmp/cloud-bandwidth

- name: run iperf server as bandwidth agent on server
  hosts: server
  vars:
    agent_image: networkstatic/iperf3:latest
    agent_port: 5201
  gather_facts: false
  pre_tasks:
    - name: install the pre-requisite apt packages
      apt: name={{ item }} state=present update_cache=false
      items:
        - docker.io
        - python-pip
      become: true

    - name: install python packages
      pip: name={{ item }}
      items:
        - docker-py
      become: true

    - name: pull networkstatic/iperf3 image
      command: docker pull {{ agent_image }}

    - name: run iperf3 server
      docker_container:
        name: iperf3-agent
        image: "{{ agent_image }}"
        ports: "{{ agent_port }}:{{ agent_port }}"
        command: -s
        detach: true
        state: started

- name: run iperf poller as bandwidth poller on client
  hosts: client
  vars:
    poller_image: networkstatic/bandwidth-poller:latest
    polling:
      count: 120
      interval_seconds: 30
      sample_count: 3
      target_address: "{{ server.ipv4 }}"
      target_type: digitalocean
      report_address: 172.17.0.2
  gather_facts: false
  tasks:
    - name: pull networkstatic/bandwidth-poller image
      command: docker pull {{ poller_image }}

    - name: run iperf3 bandwidth collector
      docker_container:
        name: iperf3-poller
        image: "{{ poller_image }}"
        state: started
        env:
          DB_IP: "{{ polling.report_address }}"
          BW_AGENT_IP: "{{ polling.target_address }}"
          MACHINE_TYPE: "{{ polling.target_type }}"
          IPERF_SAMPLE_COUNT: "{{ polling.sample_count }}"
      until: false
      retries: "{{ polling.count }}"
      delay: "{{ polling.interval_seconds }}"
      ignore_errors: true

  post_tasks:
    - name: cleanup iperf3 bandwidth poller on the client
      docker_container:
        name: iperf3-poller
        image: "{{ poller_image }}"
        state: absent

- name: cleanup iperf3 agent container on the server
  hosts: server
  gather_facts: false
  vars:
    agent_image: networkstatic/iperf3:latest
  post_tasks:
    - name: cleanup iperf3 bandwidth agent on the server
      docker_container:
        name: iperf3-agent
        image: "{{ agent_image }}"
        state: absent
